In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')

# construct a new vocabulary
alphabet = "abcdefghijklmnopqrstuvwxyz0123456789 "
char_dict = {}
for i, char in enumerate(alphabet):
    char_dict[char] = i + 1
print(char_dict)
# Use char_dict to replace the tk.word_index
tk.word_index = char_dict.copy()
# print(tk.word_index)
# Add 'UNK' to the vocabulary
tk.word_index[tk.oov_token] = max(char_dict.values()) + 1
# print(tk.word_index)

Using TensorFlow backend.


{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32, '6': 33, '7': 34, '8': 35, '9': 36, ' ': 37}


In [0]:
import pickle
with open('/content/drive/My Drive/final_spell_correction/word_index','wb') as f:
  pickle.dump(tk.word_index,f)

In [3]:
from keras.models import model_from_json
# load json and create model
json_file = open('/content/drive/My Drive/final_spell_correction/classification_words_new_space_model_noblog_cnn_bilstm_no_cunnlstm5.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model_space = model_from_json(loaded_model_json)

# load weights into new model
model_space.load_weights("/content/drive/My Drive/final_spell_correction/classification_words_new_space_model_noblog_cnn_bilstm_no_cunnlstm5.h5")
print("Loaded model from disk")

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Loaded model from disk


In [4]:
from keras.models import model_from_json
# load json and create model
json_file = open('/content/drive/My Drive/final_spell_correction/cnn_bilstm_two_word_classification.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model_two_word_spell_correction = model_from_json(loaded_model_json)

# load weights into new model
model_two_word_spell_correction.load_weights("/content/drive/My Drive/final_spell_correction/cnn_bilstm_two_word_classification.h5")
print("Loaded model from disk")

Loaded model from disk


In [0]:
# c,p = model_two_word_spell_correction.predict(np.array([1,3,5,3,4,5,34,5,6,44,5,6,4]))

In [0]:
import spacy
stop_words =['ours', 'keep', 'in', 'enough', 'anything', 'latterly'
 , 'thereupon', 'your', 'if', 'as', 'each', 'his', 'but'
 , 'everywhere', 'hereupon', 'being', 'becoming', 'and',
 'anyhow', 'serious', 'something', 'latter', 
 'namely', 'name', 'seemed', 'yourselves', 'toward', 'must', 
 'same', 'then', 'become', 'while', 'becomes', 'ourselves', 'perhaps', 
 'or', 'more', 'whose', 'along', 'own', 'thence', 'had', 'itself', 
 'top', 'whether', 'beside', 'into', 'on', 'per', 'whole', 'one', 
 'towards', 'himself', 'against', 'beyond', 'off', 'done', 'are', 
 'you', 'he', 'yours', 'an', 'myself', 'themselves', 
 'hereafter', 'else', 'have', 'neither', 'again', 'afterwards', 
 'under', 'its', 'due', 'always', 'be', 'over', 'therefore', 
 'very', 'at', 'during', 'nobody', 'where', 
 'whoever', 'across', 'thereafter', 'i', 'thereby', 'empty', 
 'move', 'put', 'through', 'since', 'my', 'wherein', 'became', 'thus',
 'none', 'cannot', 'did', 'next', 'above', 'regarding', 
 'to', 'too', 'within', 'just', 'nothing', 'now', 'am', 'part', 'seems', 'than', 'alone', 'after', 'once', 
 'doing', 'otherwise', 'who', 'indeed', 'full', 'whence',
 'before', 'how', 'although', 'mostly', 'take', 'between', 'these',
 'whereas', 'former', 'whom', 'many', 'amongst', 'other',
 'ca', 'besides', 'go', 'much', 'may', 'nowhere', 'together', 
 'him', 'her', 'there', 'say', 'throughout',
 'whereby', 'mine', 'formerly', 'only', 'really', 'herein', 
 'show', 'might', 'hers', 'often', 'when', 
 'whereupon', 'those', 'rather', 'somewhere', 'give', 'here', 
 'do', 'used', 'does', 'me', 'seem', 'unless', 'sometime', 
 'almost', 'via', 'back', 'hereby', 'few', 'all', 'up', 
 'using', 'should', 'well', 'see', 'been', 'various', 'yourself', 
 'bottom', 'onto', 'side', 'for', 'everyone', 'will', 
 'several', 'however', 'meanwhile', 'can', 'everything', 'around', 
 'she', 'of', 'their', 'were', 'get', 'until', 'that', 
 'yet', 'already', 'both', 'by', 'somehow', 'any', 'please', 
 'whereafter', 'behind', 'therein', 'the', 'they', 'whenever', 
 'out', 'still', 'our', 'most', 'least', 'though', 'with', 'a', 'could',
 'such', 'less', 'was', 'nor', 'others', 'why', 'about', 'never', 'so',
 'us', 'wherever', 'beforehand', 'moreover', 'last', 'among', 'elsewhere',
 'nevertheless', 'quite', 'upon', 'ever', 'anywhere', 'we', 'down', 'what', 
 'amount', 'whither', 'it', 'below', 'someone', 'either', 'is', 'some',
 'even', 'also', 'from', 'except', 'further', 'herself', 'make', 'which',
 'this', 'call', 'without', 'made', 're', 'sometimes', 'another', 'whatever',
 'anyone', 'would', 'every', 'thru', 'them', 'anyway', 'hence', 'has', 
 'because', 'seeming',"what's","whats",'-PRON-']
nlp = spacy.load('en', disable=['parser', 'ner'])




In [6]:
# from keras.utils import to_categorical
from numpy import argmax
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import pickle
with open('/content/drive/My Drive/two_word_spell_correction_noblog_dataset','rb') as f:
    train_texts,train_output = pickle.load(f)
train_output_1 = []
for k,i in enumerate(train_output):
    train_output_1.append(i[1])
    del train_output[k][1]

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(train_output)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[-1, :])])
print(inverted)

label_encoder_1 = LabelEncoder()
integer_encoded_1 = label_encoder_1.fit_transform(train_output_1)
print(integer_encoded_1)
# binary encode
onehot_encoder_1 = OneHotEncoder(sparse=False)
integer_encoded_1 = integer_encoded_1.reshape(len(integer_encoded_1), 1)
onehot_encoded_1 = onehot_encoder_1.fit_transform(integer_encoded_1)
print(onehot_encoded_1)
# invert first example
inverted_1 = label_encoder_1.inverse_transform([argmax(onehot_encoded_1[-1, :])])
print(inverted_1)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[62  0 40 ... 16 68 39]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['look']
[ 0 32  0 ... 57  0 55]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['print']


In [0]:
import pickle
with open('/content/drive/My Drive/final_spell_correction/label_encoder','rb') as f:
#   pickle.dump([label_encoder,label_encoder_1],f)
  label_encoder,label_encoder_1 = pickle.load(f)

In [0]:
import re
from keras.preprocessing.sequence import pad_sequences
def spell_correction(x):
  train_texts = [re.sub(r'[^\x00-\x7f]','',re.sub('[\t\r\n,)([\]!%|!#$%&*+,.-/:;<=>?@^_`{|}~?\']','',str(i))).strip().lower() for i in x]
  train_texts_split = [i.split() for i in train_texts]
  training_data = []
  for i in train_texts_split:
      for  j in i:
          if len(j) == 1  or len(j) == 2:
              pass
          else:
              try:
                  int(j)
              except:
                  training_data.append(j)
  tokensd = [tokend.lower() for tokend in training_data if not tokend.lower() in stop_words]
  doc = nlp(str(' '.join(tokensd)))
  training_data = [str(lemm.lemma_) for lemm in doc]
  train_sequences = tk.texts_to_sequences(training_data)
  train_data = pad_sequences(train_sequences, maxlen=60, padding='post')
  train_data = np.array(train_data, dtype='float32')
  splitted_words = model_space.predict(train_data)
  changed_integer = []
  for  i in splitted_words:
    changed_integer.append(np.argmax(i,axis=1))
#   print(changed_integer)
  spell_words_token = []
  temp = []
  for j in changed_integer:
    for i in j: 
      if i != 37 and i!= 0:
        temp.append(i)
      else:
        if temp != []:
          spell_words_token.append(temp)
          temp = []
  print(spell_words_token)
  for i,check_val in enumerate(spell_words_token):
    if len(check_val) <= 2:
      del spell_words_token[i]
  print(spell_words_token)
  train_data_spell = pad_sequences(spell_words_token, maxlen=13, padding='post')
#     train_data_spell = pad_sequences(spell, maxlen=13, padding='post')

  train_data_spell = np.array(train_data_spell, dtype='float32')
  corrected_word_tokenised,corrected_word_tokenised_1  = model_two_word_spell_correction.predict(train_data_spell)
  inverted = label_encoder.inverse_transform(argmax(corrected_word_tokenised,axis=1))
  inverted_1 = label_encoder_1.inverse_transform(argmax(corrected_word_tokenised_1,axis=1))
#   print(inverted,inverted_1)
  corrected_words = ''
  for i in zip(inverted,inverted_1):
    if i[1] == ' ':
      corrected_words += i[0]+i[1]
    else:
      string  = i[0]+' '+i[1]+' '
      corrected_words += string 
  print(corrected_words)

In [12]:

import time
start = time.time()
spell_correction([""])
end = time.time()
print(end - start)


[[8, 9, 4, 21, 23, 23, 5, 4, 4, 4]]
[[8, 9, 4, 21, 23, 23, 5, 4, 4, 4]]
hindu wedding 
0.06045651435852051


In [0]:
  a = np.array([2,4,5,3,5,37,4346,35,37,37,0,0,0,0,0])


In [0]:
np.where(a==37)[0]

array([5, 8, 9])

In [0]:
[x[x!=37] for x in np.split(a, np.where(a==37)[0]) if len(x[(x!=0) & (x!=37)]) ]


[array([2, 4, 5, 3, 5]), array([4346,   35])]

In [0]:
for x in np.split(a, np.where(a==37)[0]):
  print(x)

[2 4 5 3 5]
[  37 4346   35]
[37]
[37  0  0  0  0  0]
